name: Delete Demo Resource Groups

on:
  workflow_dispatch:  # manual trigger

jobs:
  delete-rgs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [centralindia, eastus, westeurope, AustraliaEast]

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete Resource Group
        run: |
          az group delete --name dsa-rg-${{ matrix.region }} --yes --no-wait
