# .github/workflows/setup-frontdoor.yml
name: Setup Azure Front Door Premium for DSA

on:
  workflow_dispatch:

jobs:
  setup-frontdoor:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Add Azure Front Door extension
        run: |
          az extension add --name front-door

      - name: Create central resource group
        run: |
          az group create --name dsa-central-rg --location centralindia

      - name: Create Front Door Premium profile
        run: |
          az afd profile create \
            --resource-group dsa-central-rg \
            --name dsa-frontdoor-profile \
            --sku Premium_AzureFrontDoor

      - name: Create backend pool with geo-filtered VMs
        run: |
          az afd origin-group create \
            --resource-group dsa-central-rg \
            --profile-name dsa-frontdoor-profile \
            --origin-group-name dsa-backends \
            --probe-request-type GET \
            --probe-protocol Http \
            --probe-path / \
            --probe-interval-in-seconds 30

          az afd origin create \
            --resource-group dsa-central-rg \
            --profile-name dsa-frontdoor-profile \
            --origin-group-name dsa-backends \
            --origin-name vm-centralindia \
            --host-name webvm-centralindia.centralindia.cloudapp.azure.com \
            --enabled-state Enabled \
            --priority 1 \
            --weight 100 \
            --location centralindia

          az afd origin create \
            --resource-group dsa-central-rg \
            --profile-name dsa-frontdoor-profile \
            --origin-group-name dsa-backends \
            --origin-name vm-eastus \
            --host-name webvm-eastus.eastus.cloudapp.azure.com \
            --enabled-state Enabled \
            --priority 1 \
            --weight 100 \
            --location eastus

          az afd origin create \
            --resource-group dsa-central-rg \
            --profile-name dsa-frontdoor-profile \
            --origin-group-name dsa-backends \
            --origin-name vm-westeurope \
            --host-name webvm-westeurope.westeurope.cloudapp.azure.com \
            --enabled-state Enabled \
            --priority 1 \
            --weight 100 \
            --location westeurope

      - name: Create endpoint and routing rule
        run: |
          az afd endpoint create \
            --resource-group dsa-central-rg \
            --profile-name dsa-frontdoor-profile \
            --endpoint-name dsa-endpoint

          az afd route create \
            --resource-group dsa-central-rg \
            --profile-name dsa-frontdoor-profile \
            --endpoint-name dsa-endpoint \
            --route-name dsa-route \
            --origin-group dsa-backends \
            --https-redirect Enabled \
            --supported-protocols Http Https \
            --patterns-to-match /* \
            --forwarding-protocol MatchRequest \
            --enabled-state Enabled
